### PR TITLE
Removed uglify and concat from the build process

### PR DESCRIPTION
**Pull request by aminmarashi**

### CODE REVIEW

**Comment by aminmarashi** [comment]
This change requires cairo to work,``` brew install cairo```

**Comment by negar-binary** [comment]
@aminmarashi can you add that to the read me file? to use `brew install cairo`

**Comment by aminmarashi** [comment]
@negar-binary @binary-hamedanchi I removed canvas and jsdom from optional dependencies. cairo is no longer needed.

**Comment by negar-binary** [comment]
@aminmarashi great, thanks

**Comment by aminmarashi** [comment]
@

**Pull request merged**
