### PR TITLE
Refactor list styles, only one style remains

### PR DESCRIPTION
**Pull request by borisyankov**
The class name 'bullet' is kept, because it is universal, though the style is actually of a check mark.

### CODE REVIEW

**Comment by raunakkathuria** [comment]
Why translations files are added in pull request?

**Comment by borisyankov** [comment]
Because of the <ul class='checked'> line being included in them.
Should we rework the translation files or?

**Comment by raunakkathuria** [comment]
Can you remove the translation file, as it is automated process they will added themselves

**Comment by borisyankov** [comment]
Sure.

**Pull request closed without merging**
