### PR TITLE
Optimize images for shrinkray-1

### PR DESCRIPTION
**Pull request by jy-binary**

### CODE REVIEW

**Comment by jy-binary** [comment]
Images shrunk 50.52% (11944b -> 5911b)


* binary-static/src/images/email/facebook.png (565b -> 289b)
* binary-static/src/images/email/googleplus.png (650b -> 350b)
* binary-static/src/images/email/linkedin.png (594b -> 316b)
* binary-static/src/images/email/logo.png (5695b -> 2173b)
* binary-static/src/images/email/twitter.png (655b -> 348b)
* binary-static/src/images/email/webinar.png (2956b -> 2028b)
* binary-static/src/images/email/youtube.png (829b -> 407b)

**Comment by jy-binary** [comment]
Images shrunk 27.8% (1162b -> 839b)


* binary-static/src/images/common/question_1.png (222b -> 220b)
* binary-static/src/images/email/daily_report.png (703b -> 398b)
* binary-static/src/images/email/line_icon.png (237b -> 221b)

**Comment by jy-binary** [comment]
Images shrunk 30.78% (68545b -> 47452b)


* binary-static/src/images/email/trading_room.png (477b -> 251b)
* binary-static/src/images/favicons/apple-touch-icon.png (11100b -> 7703b)
* binary-static/src/images/favicons/favicon-160x160.png (9924b -> 6805b)
* binary-static/src/images/favicons/favicon-16x16.png (1203b -> 885b)
* binary-static/src/images/favicons/favicon-192x192.png (11855b -> 8234b)
* binary-static/src/images/favicons/favicon-32x32.png (1924b -> 1217b)
* binary-static/src/images/favicons/favicon-96x96.png (5576b -> 3665b)
* binary-static/src/images/favicons/mstile-144x144.png (8882b -> 5870b)
* binary-static/src/images/favicons/mstile-150x150.png (8466b -> 6007b)
* binary-static/src/images/favicons/mstile-310x150.png (9138b -> 6815b)

**Comment by jy-binary** [comment]
Images shrunk 26.68% (24615b -> 18048b)


* binary-static/src/images/favicons/mstile-310x310.png (18619b -> 14116b)
* binary-static/src/images/favicons/mstile-70x70.png (5996b -> 3932b)

**Comment by jy-binary** [comment]
Images shrunk 0.5% (407b -> 405b)


* binary-static/src/images/pages/trade/ends-between_1.png (193b -> 192b)
* binary-static/src/images/pages/trade/ends-outside_1.png (214b -> 213b)

**Comment by jy-binary** [comment]
Images shrunk 51.07% (8331b -> 4077b)


* binary-static/src/images/pages/get-started/list-circle_1.png (369b -> 302b)
* binary-static/src/images/pages/get-started/spreadbet-howto.png (3576b -> 1306b)
* binary-static/src/images/pages/home/xicon-1.png (1045b -> 590b)
* binary-static/src/images/pages/home/xicon-2.png (1035b -> 571b)
* binary-static/src/images/pages/home/xicon-3.png (981b -> 528b)
* binary-static/src/images/pages/home/xicon-4.png (1039b -> 564b)
* binary-static/src/images/pages/light_chart/linechart_legends_1.png (286b -> 216b)

**Comment by jy-binary** [comment]
Images shrunk 25.9% (18932b -> 14030b)


* binary-static/src/images/pages/trade/fall_1.png (271b -> 261b)
* binary-static/src/images/pages/trade/higher_1.png (253b -> 251b)
* binary-static/src/images/pages/trade/no-touch_1.png (284b -> 279b)
* binary-static/src/images/pages/trade/rise_1.png (265b -> 257b)
* binary-static/src/images/pages/trade/stay-out_1.png (369b -> 364b)
* binary-static/src/images/pages/trade/touch_1.png (250b -> 248b)
* binary-static/src/images/pages/binary-symbol-logo.png (5769b -> 3782b)
* binary-static/src/css/external/jquery-ui-custom-theme/images/ui-icons_222222_256x240.png (6922b -> 4431b)
* binary-static/src/css/external/jquery-ui-custom-theme/images/ui-icons_2e83ff_256x240.png (4549b -> 4157b)

**Comment by jy-binary** [comment]
Images shrunk 31.68% (65563b -> 44794b)


* binary-static/src/css/external/jquery-ui-custom-theme/images/ui-icons_454545_256x240.png (6992b -> 4431b)
* binary-static/src/css/external/jquery-ui-custom-theme/images/ui-icons_888888_256x240.png (6999b -> 4431b)
* binary-static/src/css/external/jquery-ui-custom-theme/images/ui-icons_cd0a0a_256x240.png (4549b -> 4157b)
* binary-static/src/images/common/nav/menu-sub-selection_1.png (148b -> 146b)
* binary-static/src/images/favicons/apple-touch-icon-114x114.png (6915b -> 4556b)
* binary-static/src/images/favicons/apple-touch-icon-120x120.png (7375b -> 4849b)
* binary-static/src/images/favicons/apple-touch-icon-144x144.png (8840b -> 5974b)
* binary-static/src/images/favicons/apple-touch-icon-152x152.png (9347b -> 6402b)
* binary-static/src/images/favicons/apple-touch-icon-180x180.png (11100b -> 7703b)
* binary-static/src/images/favicons/apple-touch-icon-57x57.png (3298b -> 2145b)

**Comment by jy-binary** [comment]
Images shrunk 33.81% (23225b -> 15373b)


* binary-static/src/images/favicons/apple-touch-icon-60x60.png (3447b -> 2228b)
* binary-static/src/images/favicons/apple-touch-icon-72x72.png (4160b -> 2695b)
* binary-static/src/images/favicons/apple-touch-icon-76x76.png (4392b -> 2868b)
* binary-static/src/images/favicons/apple-touch-icon-precomposed.png (11226b -> 7582b)

**Comment by jy-binary** [comment]
Images shrunk 2.37% (1521b -> 1485b)


* binary-static/src/images/pages/trade/stay-in-between_1.png (312b -> 305b)
* binary-static/src/css/external/jquery-ui-custom-theme/images/ui-bg_glass_55_fbf9ee_1x400.png (335b -> 332b)
* binary-static/src/css/external/jquery-ui-custom-theme/images/ui-bg_glass_75_e6e6e6_1x400.png (262b -> 260b)
* binary-static/src/css/external/jquery-ui-custom-theme/images/ui-bg_glass_95_fef1ec_1x400.png (332b -> 329b)
* binary-static/src/css/external/jquery-ui-custom-theme/images/ui-bg_highlight-soft_75_cccccc_1x100.png (280b -> 259b)

**Comment by borisyankov** [comment]
Not so sure about all of the optimizations.
We talked with Raunak a month ago that these are best done via grunt (easy to do).

Also some of the files have already been optimized (hard to tell which ones), but for ones that do not compress well, better skip them. 
This compression is lossy, and doing it twice will cause issues.

**Comment by raunakkathuria** [comment]
Lets not commit compressed files in master (we used to do it earlier) better have grunt task handle it and push to gh-pages only

**Pull request closed without merging**
