### PR TITLE
kelly/change_OTC_Indices_to_Indices

### PR DESCRIPTION
**Pull request by kellybinary**
- change OTC Indices to Indices

### CODE REVIEW

**Comment by negarn** [comment]
probably our active symbols test will start failing, but we can update it after BE releases

**Comment by ashkanx** [comment]
I think BE released the changed

**Comment by negarn** [comment]
@kellybinary then can you update the test as well please?

**Comment by kellybinary** [comment]
@negarn which test are we talking about?

**Comment by negarn** [comment]
https://github.com/binary-com/binary-static/blob/master/src/javascript/app/common/__tests__/active_symbols.js#L9

**Pull request merged**
