### PR TITLE
Use Roboto font

### PR DESCRIPTION
**Pull request by borisyankov**
Replaces Proxima font with Roboto font, loaded from Google Fonts.
Several font weight adjustments.
Supports Vietnamese

### CODE REVIEW

**Comment by ashkanx** [comment]
@borisyankov 
I think this is a major UI change. Can we see it in QA before going live?

**Comment by raunakkathuria** [comment]
@ashkanx @borisyankov the change is deployed on qa11 please check

**Comment by ashkanx** [comment]
@raunakkathuria Thanks

**Comment by ashkanx** [comment]
@borisyankov @raunakkathuria 
This has been approved by JY & can be released. Thanks.

**Pull request merged**
