### PR TITLE
Mention R_10 index

### PR DESCRIPTION
**Pull request by basiliscos**

### CODE REVIEW

**Comment by ashkanx** [comment]
@basiliscos when is this planned to go live? is there any card for this in Trello?

**Comment by basiliscos** [comment]
@ashkanx https://trello.com/c/PpoVnRMf/3415-ivan-r-10-r2-10 

Afaik in is planned to be released rather soon with next grey release

**Comment by ashkanx** [comment]
Thanks. Please remind me, so I release this too

**Comment by jy-binary** [comment]
can you add me as a collaborator in your fork so I can see the Update Branch button?

**Pull request merged**
