### PR TITLE
binary-maksym/new-layout

### PR DESCRIPTION
**Pull request by binary-maksym**

### CODE REVIEW

**Comment by mwmiller** [comment]
Could you clean up this history with some informative commit messages?

**Comment by borisyankov** [comment]
Looks good.

**Comment by borisyankov** [comment]
But yeah, Matt is correct, we need to have better history, and not accept no commits.
Next time rebase, ok?

**Comment by binary-maksym** [comment]
Sure

On Fri, Sep 25, 2015 at 5:58 PM, Boris Yankov <notifications@github.com>
wrote:

> But yeah, Matt is correct, we need to have better history, and not accept
> no commits.
> Next time rebase, ok?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/binary-com/binary-static/pull/497#issuecomment-143175809>
> .
>



-- 
[image: photo] <http://www.facebook.com/catavary>
<http://www.linkedin.com/pub/maksym-kotielnikov/b3/b38/6b2>Maksym
Kotielnikov
Software Engineer, Binary Group Services Sdn. Bhd.
011-3517-2930  <011-3517-2930>// Skype: maxim_kotelnikov

**Pull request merged**
