### PR TITLE
Adding 4 new landing pages, remove home3/4/5

### PR DESCRIPTION
**Pull request by ashkanx**

### CODE REVIEW

**Comment by raunakkathuria** [comment]
are these png images compressed?

**Comment by borisyankov** [comment]
I think we doing it wrong ;)
We should have kept the .png and .svgs in the original state, and do the compression in the build process.

**Comment by raunakkathuria** [comment]
@borisyankov ok then we will find grunt plugin for this so that only compressed images go to gh-pages

**Comment by ashkanx** [comment]
Sorry Boris, Already compressed  :)
Raunak will talk to you about this

**Pull request merged**
